# Generated by Django 3.1.1 on 2020-09-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_projectname1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectMembers',
        ),
    ]
