# Generated by Django 3.1.1 on 2020-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_projectmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectMembers',
            field=models.CharField(default='No Members', max_length=32),
        ),
    ]
