# Generated by Django 3.1.1 on 2020-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_projectmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
