# Generated by Django 3.1.1 on 2020-10-05 05:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_project_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='posts/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
