# Generated by Django 3.1.1 on 2020-10-07 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201005_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCreatedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='projectCreatedBy',
            field=models.CharField(default='User', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='projectModifiedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='projectModifiedBy',
            field=models.CharField(default='User', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='projectStatus',
            field=models.BooleanField(default=True),
        ),
    ]
