# Generated by Django 3.1.1 on 2020-10-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201007_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectCreatedAt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectModifiedAt',
        ),
    ]
