# Generated by Django 3.1.1 on 2020-10-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201007_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectCreatedAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='projectModifiedAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
