# Generated by Django 3.1.1 on 2020-10-07 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201007_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCreatedAt',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 7, 15, 6, 110501)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectModifiedAt',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 7, 15, 6, 110517)),
        ),
    ]
