# Generated by Django 3.1.1 on 2020-10-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201007_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCreatedAt',
            field=models.CharField(default='2020-10-07 07:26:00', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectModifiedAt',
            field=models.CharField(default='2020-10-07 07:26:00', max_length=32),
        ),
    ]
