# Generated by Django 3.1.1 on 2020-10-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201007_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
