# Generated by Django 3.1.1 on 2020-10-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201007_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
