# Generated by Django 3.1.1 on 2020-10-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
