# Generated by Django 3.1.1 on 2020-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='ddfs', max_length=32),
        ),
    ]
